import "oaidl.idl";
import "ocidl.idl";

namespace CoronaWinUi
{
    enum FieldTypes
    {
        FieldNone,
        FieldDouble,
        FieldInt64,
        FieldString,
        FieldDateTime,
        FieldObject,
        FieldArray,
        FieldReference,
        FieldFunction,
        FieldQuery,
        FieldBlob
    };

    interface IFieldOptions
    {

    };

    runtimeclass DoubleFieldOptions : IFieldOptions
    {
        Double MinValue ;
        Double MaxValue ;
        String Message ;
    };

    runtimeclass Int64FieldOptions : IFieldOptions
    {
        Int64  MinValue ;
        Int64  MaxValue ;
        String Message ;
    };

    runtimeclass DateTimeFieldOptions : IFieldOptions
    {
        DateTime  MinValue ;
        DateTime  MaxValue ;
        DateTime  Message ;
    };

    runtimeclass ArrayFieldOptions : IFieldOptions
    {
        FieldTypes                                     FundamentalType ;
        Windows.Foundation.Collections.IVector<String> AllowedBaseClasses ;
        Windows.Foundation.Collections.IVector<String> AllowedClasses ;
    };

    runtimeclass ObjectFieldOptions : IFieldOptions
    {
        FieldTypes                                     FundamentalType ;
        Windows.Foundation.Collections.IVector<String> AllowedBaseClasses;
        Windows.Foundation.Collections.IVector<String> AllowedClasses ;
    };

    runtimeclass BasicFilter
    {
        String FieldName ;
        String FieldValue ;
    }

    runtimeclass QueryFrom 
    {
        String ClassName ;
        String Name ;
        Windows.Foundation.Collections.IVector<BasicFilter> Filters ;
    }

    interface IQueryStage
    {
        String StageName ;
    }

    interface IQueryCondition
    {
        String ClassName ;
    }

    runtimeclass QueryConditionLt : IQueryCondition
    {
        String ValuePath ;
        String Value  ;
    }  

    runtimeclass QueryConditionLtEq: IQueryCondition
    {
        String ValuePath  ;
        String Value  ;
    }  

    runtimeclass QueryConditionEq: IQueryCondition
    {
        String ValuePath ;
        String Value ;
    }  

    runtimeclass QueryConditionGtEq: IQueryCondition
    {
        String ValuePath  ;
        String Value ;
    }  

    runtimeclass QueryConditionContains: IQueryCondition
    {
        String ValuePath ;
        String Value ;
    }  

    runtimeclass QueryConditionAll: IQueryCondition
    {
        String ValuePath ;
        String Value ;
        Windows.Foundation.Collections.IVector<ICondition> Conditions ;
    }

    runtimeclass QueryConditionAny: IQueryCondition
    {
        String ValuePath ;
        String Value ;
        Windows.Foundation.Collections.IVector<ICondition> Conditions ;
    }  

    runtimeclass QueryConditionNone: IQueryCondition
    {
        Windows.Foundation.Collections.IVector<ICondition> Conditions ;
    }  

    runtimeclass QueryFilter: IQueryStage
    {
        IQueryCondition Condition ;
    }

    runtimeclass QueryJoin: IQueryStage
    {
        String Source1 ;
        String Source2 ;
        String ResultName1 ;
        String ResultName2 ;
        Windows.Foundation.Collections.IVector<String> Keys ;
    }

    runtimeclass QueryProjectField
    {
        String FieldName ;
        String ValuePath ;
    }

    runtimeclass QueryProject: IQueryStage
    {
        String SourceName ;
        Windows.Foundation.Collections.IVector<QueryProjectField> Projection ;
    }

    runtimeclass Query
    {
        QueryFrom From ;
        Windows.Foundation.Collections.IVector<IQueryStage> Stages ;
    }
    
    runtimeclass QueryFieldOptions : IFieldOptions
    {
        Query QueryBody ;
    };

    runtimeclass FieldDefinition
    {
        FieldTypes              FieldType ;
        String                  FieldName ;
        String                  FieldDescription ;
        IFieldOptions           FieldOptions ;
    };

    runtimeclass IndexDefinition
    {
        String                  IndexName ;
        Windows.Foundation.Collections.IVector<String> IndexKeys ;
    };

    runtimeclass ClassDefinition
    {
        String ClassName ;
        String ClassDescription ;
        String BaseClassName ;
        Windows.Foundation.Collections.IVector<FieldDefinition> Fields ;
        Windows.Foundation.Collections.IVector<IndexDefinition> Indexes ;
        Windows.Foundation.Collections.IVector<String> DescendantClasses ;
        Windows.Foundation.Collections.IVector<String> AncestorClasses ;
    };

    interface IBaseResponse
    {
        bool   Success ;
        String Message ;
        Double ExecutionTimeSeconds ;
    };

    interface ICoronaBaseObject
    {
        JsonObject Data;
    };

    interface ICoronaObject : ICoronaBaseObject
    {
        String ClassName;
        int64 ObjectId;
        DateTime Created;
        String CreatedBy;
        DateTime Updated;
        String UpdatedBy;
    };

    runtimeclass CoronaBaseObject : ICoronaBaseObject
    {
    };

    runtimeclass CoronaObject : ICoronaObject
    {
    };

    runtimeclass CoronaUser : ICoronaObject
    {
        String UserName ;
        String Email ;
        String Address1 ;
        String Address2 ;
        String City ;
        String State ;
        String Zip ;
    };

    runtimeclass CreateUserRequest {
        String Username ;
        String Email ;
        String Address1 ;
        String Address2 ;
        String City ;
        String State ;
        String Zip ;
        String Password1 ;
        String Password2 ;
    };

    runtimeclass CreateUserResponse : IBaseResponse {
        CoronaUser Data ;
    }

    runtimeclass LoginUserRequest {
        String UserName ;
        String Password ;
    }
    runtimeclass LoginUserResponse: IBaseResponse {
        CoronaUser Data ;
    }

    runtimeclass ConfirmUserRequest {
        String Email ;
        String ValidationCode ;
    }
    runtimeclass ConfirmUserResponse : IBaseResponse {
        CoronaUser Data ;
    }

    runtimeclass SendUserRequest {
        String Email ;
    }
    runtimeclass SendUserResponse : IBaseResponse{
        CoronaUser Data ;
    }

    runtimeclass PasswordUserRequest {
        String UserName ;
        String ValidationCode ;
        String Password1 ;
        String Password2 ; 
    }
    runtimeclass PasswordUserResponse : IBaseResponse{
        CoronaUser Data ;
    }



    runtimeclass GetClassRequest {
        String ClassName;
    }
    runtimeclass GetClassResponse : IBaseResponse{
        Windows.Foundation.Collections.IVector<ClassDefinition> Classes;
    }

    runtimeclass GetClassesRequest {
        ;
    }
    runtimeclass GetClassesResponse : IBaseResponse{
        Windows.Foundation.Collections.IVector<ClassDefinition> Classes;
    }

    runtimeclass PutClassesRequest {
        ClassDefinition ClassDef;
    }
    runtimeclass PutClassesResponse: IBaseResponse {
        CoronaObject Data;
    }

    runtimeclass GetObjectsRequest {
        ;
    }
    runtimeclass GetObjectsResponse : IBaseResponse{
        CoronaObject Data;
    }

    runtimeclass PutObjectsRequest {
        ;
    }
    runtimeclass PutObjectsResponse : IBaseResponse{
        CoronaObject Data;
    }

    runtimeclass QueryObjectsRequest {
        ;
    }
    runtimeclass QueryObjectsResponse : IBaseResponse{
        CoronaBaseObject Data;
    }

    runtimeclass DeleteObjectsRequest {
        ;
    }
    runtimeclass DeleteObjectsResponse : IBaseResponse{
        CoronaObject Data;
    }

    runtimeclass CreateObjectsRequest {
        String ClassName;
    }
    runtimeclass CreateObjectsResponse : IBaseResponse{
        CoronaObject Data;
    }

    runtimeclass EditObjectRequest {
        String ClassName;
        int64  ObjectId;
    }
    runtimeclass EditObjectResponse : IBaseResponse{
        CoronaObject Data;
    }

    runtimeclass RunObjectRequest {
        CoronaObject Data;
    }
    runtimeclass RunObjectResponse : IBaseResponse{
        CoronaObject Data;
    }

    runtimeclass CopyObjectPath 
    {
        String ClassName;
        String Path;
    }

    runtimeclass CopyObjectRequest {
        CopyObjectPath      Source;
        CopyObjectPath      Dest;
        CopyObjectPath      Transform;
    }
    runtimeclass CopyObjectResponse : IBaseResponse{
        CoronaObject Data;
    }

    interface ICoronaClient
    {
        bool Open();
        bool Close();
        
        Windows.Foundation.IAsyncOperation<CreateUserResponse> CreateUser(CreateUserRequest);
        Windows.Foundation.IAsyncOperation<LoginUserResponse> LoginUser(LoginUserRequest);
        Windows.Foundation.IAsyncOperation<ConfirmUserResponse> ConfirmUser(ConfirmUserRequest);
        Windows.Foundation.IAsyncOperation<SendUserResponse> SendUser(SendUserRequest);
        Windows.Foundation.IAsyncOperation<PasswordUserResponse> PasswordUser(PasswordUserRequest);
        Windows.Foundation.IAsyncOperation<GetClassResponse> GetClass(GetClassRequest);
        Windows.Foundation.IAsyncOperation<GetClassesResponse> GetClasses(GetClassesRequest);
        Windows.Foundation.IAsyncOperation<PutClassesResponse> PutClasses(PutClassesRequest);
        Windows.Foundation.IAsyncOperation<GetObjectsResponse> GetObjects(GetObjectsRequest);
        Windows.Foundation.IAsyncOperation<PutObjectsResponse> PutObjects(PutObjectsRequest);
        Windows.Foundation.IAsyncOperation<QueryObjectsResponse> QueryObjects(QueryObjectsRequest);
        Windows.Foundation.IAsyncOperation<DeleteObjectsResponse> DeleteObjects(DeleteObjectsRequest);
        Windows.Foundation.IAsyncOperation<CreateObjectResponse> CreateObject(CreateObjectRequest);
        Windows.Foundation.IAsyncOperation<EditObjectResponse> EditObject(EditObjectRequest);
        Windows.Foundation.IAsyncOperation<RunObjectRequest> RunObject(RunObjectRequest);
        Windows.Foundation.IAsyncOperation<CopyObjectRequest> CopyObject(CopyObjectRequest);
        
    }

    runtimeclass LocalCoronaClient : ICoronaClient
    {
        String FileName 
    }

    runtimeclass RemoteCoronaClient : ICoronaClient
    {
        String HostName;
        Int32  Port;
        String Url;
        
    }

}
