/*
CORONA
C++ Low Code Performance Applications for Windows SDK
by Todd Bandrowky
(c) 2024 + All Rights Reserved

About this File

Notes

For Future Consideration
*/


#ifndef CORONA_DATATRANSFER_H
#define CORONA_DATATRANSFER_H

namespace corona
{
	using ccolor = D2D1_COLOR_F;

	class directException {
	public:
		std::string message;
		unsigned int lastError;
	};

	enum dtoIconId
	{
		STOCKICO_DOCNOASSOC = 0,
		STOCKICO_DOCASSOC = 1,
		STOCKICO_APPLICATION = 2,
		STOCKICO_FOLDER = 3,
		STOCKICO_FOLDEROPEN = 4,
		STOCKICO_DRIVE525 = 5,
		STOCKICO_DRIVE35 = 6,
		STOCKICO_DRIVEREMOVE = 7,
		STOCKICO_DRIVEFIXED = 8,
		STOCKICO_DRIVENET = 9,
		STOCKICO_DRIVENETDISABLED = 10,
		STOCKICO_DRIVECD = 11,
		STOCKICO_DRIVERAM = 12,
		STOCKICO_WORLD = 13,
		STOCKICO_SERVER = 15,
		STOCKICO_PRINTER = 16,
		STOCKICO_MYNETWORK = 17,
		STOCKICO_FIND = 22,
		STOCKICO_HELP = 23,
		STOCKICO_SHARE = 28,
		STOCKICO_LINK = 29,
		STOCKICO_SLOWFILE = 30,
		STOCKICO_RECYCLER = 31,
		STOCKICO_RECYCLERFULL = 32,
		STOCKICO_MEDIACDAUDIO = 40,
		STOCKICO_LOCK = 47,
		STOCKICO_AUTOLIST = 49,
		STOCKICO_PRINTERNET = 50,
		STOCKICO_SERVERSHARE = 51,
		STOCKICO_PRINTERFAX = 52,
		STOCKICO_PRINTERFAXNET = 53,
		STOCKICO_PRINTERFILE = 54,
		STOCKICO_STACK = 55,
		STOCKICO_MEDIASVCD = 56,
		STOCKICO_STUFFEDFOLDER = 57,
		STOCKICO_DRIVEUNKNOWN = 58,
		STOCKICO_DRIVEDVD = 59,
		STOCKICO_MEDIADVD = 60,
		STOCKICO_MEDIADVDRAM = 61,
		STOCKICO_MEDIADVDRW = 62,
		STOCKICO_MEDIADVDR = 63,
		STOCKICO_MEDIADVDROM = 64,
		STOCKICO_MEDIACDAUDIOPLUS = 65,
		STOCKICO_MEDIACDRW = 66,
		STOCKICO_MEDIACDR = 67,
		STOCKICO_MEDIACDBURN = 68,
		STOCKICO_MEDIABLANKCD = 69,
		STOCKICO_MEDIACDROM = 70,
		STOCKICO_AUDIOFILES = 71,
		STOCKICO_IMAGEFILES = 72,
		STOCKICO_VIDEOFILES = 73,
		STOCKICO_MIXEDFILES = 74,
		STOCKICO_FOLDERBACK = 75,
		STOCKICO_FOLDERFRONT = 76,
		STOCKICO_SHIELD = 77,
		STOCKICO_WARNING = 78,
		STOCKICO_INFO = 79,
		STOCKICO_ERROR = 80,
		STOCKICO_KEY = 81,
		STOCKICO_SOFTWARE = 82,
		STOCKICO_RENAME = 83,
		STOCKICO_DELETE = 84,
		STOCKICO_MEDIAAUDIODVD = 85,
		STOCKICO_MEDIAMOVIEDVD = 86,
		STOCKICO_MEDIAENHANCEDCD = 87,
		STOCKICO_MEDIAENHANCEDDVD = 88,
		STOCKICO_MEDIAHDDVD = 89,
		STOCKICO_MEDIABLURAY = 90,
		STOCKICO_MEDIAVCD = 91,
		STOCKICO_MEDIADVDPLUSR = 92,
		STOCKICO_MEDIADVDPLUSRW = 93,
		STOCKICO_DESKTOPPC = 94,
		STOCKICO_MOBILEPC = 95,
		STOCKICO_USERS = 96,
		STOCKICO_MEDIASMARTMEDIA = 97,
		STOCKICO_MEDIACOMPACTFLASH = 98,
		STOCKICO_DEVICECELLPHONE = 99,
		STOCKICO_DEVICECAMERA = 100,
		STOCKICO_DEVICEVIDEOCAMERA = 101,
		STOCKICO_DEVICEAUDIOPLAYER = 102,
		STOCKICO_NETWORKCONNECT = 103,
		STOCKICO_INTERNET = 104,
		STOCKICO_ZIPFILE = 105,
		STOCKICO_SETTINGS = 106,
		STOCKICO_DRIVEHDDVD = 132,
		STOCKICO_DRIVEBD = 133,
		STOCKICO_MEDIAHDDVDROM = 134,
		STOCKICO_MEDIAHDDVDR = 135,
		STOCKICO_MEDIAHDDVDRAM = 136,
		STOCKICO_MEDIABDROM = 137,
		STOCKICO_MEDIABDR = 138,
		STOCKICO_MEDIABDRE = 139,
		STOCKICO_CLUSTEREDDRIVE = 140,
		STOCKICO_MAX_ICONS = 175
	};

}

#endif
